name: Generate JSON on Push or PR

on: [workflow_dispatch, push]

jobs:
  generate-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.actor != 'github-actions[bot]' && github.event_name != 'push' || github.event.pusher.name != 'github-actions[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for full meta history

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git config --global core.quotePath false

      - name: get inputs for job
        run: |
          all_files=$(git ls-tree -r --name-only HEAD)
          files_modified=$(git diff --name-only HEAD~1 HEAD)
          existing_meta=$(cat metadata.json)
          echo "all_files=$all_files" >> $GITHUB_ENV
          echo "files_modified=$files_modified" >> $GITHUB_ENV
          echo "existing_meta=$existing_meta" >> $GITHUB_ENV
      - name: Run dates.js
        uses: ./actions/dates
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          all-files: ${{ env.all_files }}
          files-modified: ${{ env.files_modified }}
          existing-meta: ${{ env.existing_meta }}

      - name: Commit if different
        run: |
          git add metadata.json
          git commit -m "Automated Update of metadata.json with latest file dates" || echo "No changes to commit"
          git push || echo "No changes to push"
