name: Generate JSON on Push or PR

on: [workflow_dispatch, push]

jobs:
  generate-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.actor != 'github-actions[bot]' && github.event_name != 'push' || github.event.pusher.name != 'github-actions[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git config --global core.quotePath false

      - name: Get dates meta
        run: |
          # Generate the JSON and save to output.json
          output=$(git ls-tree -r --name-only HEAD | grep -v '/\.' | grep -v '^\.')
          json="{"

          echo "${output}" | while read -r filename; do
            date=$(git log -1 --format="%aD" -- "$filename")
            json+="\"${filename}\": \"${date}\", "
          done

          # Remove the trailing comma and space
          json=${json%, }
          json+="}"

          # Write to output.json
          echo "${json}" > output.json

      - name: Commit if different
        run: |
          git add output.json
          git commit -m "Automated Update of output.json with latest file dates"
          git push
